config/routes.rb
Rails.application.routes.draw do
 
  get 'orders/new'

  get 'orders/create'

  get 'sessions/new'

  get 'users/new'

  get 'record/index'

  get 'record/show'

  get 'genre/index'

  get 'genre/show'

  get 'admin', to: 'admin/admin_users#index'

  get '/index', to: 'welcome#index', as: 'welcome'

  get 'record/index', to: 'record#index', as: 'records'

  post 'record/index'
  post 'record/:id', to: 'record#show'
  post 'record/:id/add', to: 'record#add', as: 'add_record'

  post '/index', to: 'welcome#index'

  get "/log_in", to: "sessions#new", as: "log_in"
  post "/log_in", to: "sessions#create"

  get "/log_out", to: "sessions#destroy", as: "log_out"

  get "/sign_up", to: "users#new", as: "sign_up"

  post '/users', to: 'users#create'
  post 'users/:id', to: 'users#show'
  post 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  delete '/users/:id', to: "users#destroy", as: 'destroy_user'

  post '/baskets/:id', to: 'baskets#show', as: 'show_basket'
  post '/baskets/:id/remove_product(:record_id)', to: 'baskets#remove_product', as: 'remove_product'

  post 'orders/create', to: 'orders#create', as: 'create_order'
  post 'orders/index', to: 'orders#index', as: 'orders_index'

  resources :artist, :genre, :record, :sessions, :users, :baskets, :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :records
  validates :name, presence: true, uniqueness: true
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  serialize :products, Hash

  def add(record)
    unless products[record]
      products[record] = 1
    else
      products[record] += 1
    end
    products
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :records
  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  serialize :products, Hash

  validates :total, presence: true

  enum status: [ :anulowane, :przyjęte_do_realizacji, :w_trakcie_realizacji, :wysłane ]
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :artist
  belongs_to :genre

  validates_presence_of :artist , :genre, :name
  validates_associated :artist , :genre
  validates :price, 
    :numericality => {:greater_than_or_equal_to => 0},
    presence: true
  validates :release_year, 
    :numericality => {:greater_than => 1500, :less_than_or_equal_to => Time.now.year},
    presence: true

  def self.search_(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders

  has_secure_password
  
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_confirmation_of :password, :message => 'Hasła do siebie nie pasują', :allow_blank => true
  validates :password,:presence => {:message => 'Hasło jest wymagane!'}
  validates :password_confirmation,:presence => {:message => 'Potwierdzenie hasła jest wymagane!'}
  validates_length_of :password, :minimum => 5, :message => 'Za krótkie hasło (co najmniej 5 znaków)', :allow_blank => true
  validates_presence_of :email, :message => 'Adres email jest wymagany!'
  validates_uniqueness_of :email, :message => 'Użytkownik o podanym adresie już istnieje!'
  validates :email, :format => EMAIL_REGEX, :allow_blank => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to log_in_path unless current_user
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  helper_method :remove_product

  def new
    @basket = Basket.new(params[:id])
  end

  def create
    @basket = Basket.new(params[:id])
    @basket.save!
  end

  def show
    @basket = Basket.find(session[:basket_id])
  end

  def remove_product
    basket = Basket.find(session[:basket_id])
    record = Record.find(params[:record_id])
    basket.update(products: basket.products.except(record))
    redirect_to show_basket_path(basket)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authorize

  def index
    @orders = Order.where(user_id: current_user)
  end

  def create
    @order =  Order.new(user: current_user, total: params[:total], products: params[:products])
    session[:basket_id] = nil
    if @order.save!
      redirect_to root_path, notice: "Przyjęto zamówienie nr #{@order.id}"
    else 
      redirect_to root_path, notice: 'Nie udało się'
    end
  end

  def show
  end

end

app/controllers/record_controller.rb
class RecordController < ApplicationController
  handles_sortable_columns

  def index
    @records = Record.all

    order = sortable_column_order do |column, direction|
      case column
        when "record_name" 
          "name #{direction}"
        when "artist_name"
          #@records = @records.includes(:artist)
          #{}"artist.name #{direction}"
        when "genre"
          #@records = @records.includes(:genre)
          #{}"genre.name #{direction}"
        when "release_year"
          "release_year #{direction}"
        when "price"
          "price #{direction}"
      end
    end

    @records = @records.search_(params[:search]).order(order).paginate(per_page: 10, page: params[:page])
  end

  def show
    @record = Record.find(params[:id])
  end

  def add
    session[:basket_id] ||= Basket.create.id
    record = Record.find(params[:id])
    Basket.find(session[:basket_id]).update(products: Basket.find(session[:basket_id]).add(record))
    redirect_to records_path, notice: 'Dodano do koszyka'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Zarejestrowano!"
    else
      flash[:alert] = []
      @user.errors.values.flatten.each do |message|
        flash[:alert] << message    
      end
      redirect_to sign_up_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    session[:user_id] = nil
    user.destroy
    redirect_to root_path
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(user_params)
      redirect_to user_path(user[:id]), notice: "Zaktualizowano dane"
    else
      redirect_to edit_user_path(user[:id]), notice: "Edycja nie powiodła się"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def initialize_basket
    basket = Basket.create
    session[:basket_id] = basket.id
  end
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/baskets/show.html.erb
<% unless @basket.products.empty? %>
  <table>
    <thead>
      <tr height="25">
        <th></th>
        <th>Produkt</th>
        <th>Ilość</th>
        <th>Cena</th>
        <th></th>
        <th></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <tr height='10'></tr>
      <% total = 0 %>
      <% @basket.products.each do |record, number| %>
        <tr>
          <% album_cover_path = 'album covers/' + record.name.downcase.gsub(/\s/,'_') + '.jpg' %>
          <% album_cover_path = 'question_mark.png' if !File.exist?("#{Rails.root}/app/assets/images/" + album_cover_path) %>
          <td><%=image_tag(album_cover_path, height: '45', width: '45')%></td>
          <td><b><%= record.artist.name + ' - ' + record.name %></b></td>
          <td><b><%= number %></b></td>
          <% total += record.price * number %>
          <td><b><%= (record.price * number).to_s + '0 zł'%></b></td>
          <td><%= button_to 'Więcej', record %></td>
          <td><%= button_to 'Usuń', remove_product_path(record_id: record.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="action_buttons_header" style="text-align: right;">
    <ul style="list-style: none">
      <li><b>W sumie do zapłaty: <%= total.to_s + '0 zł' %></b></li><br>
      <li><%= button_to 'Złóż zamówienie', create_order_path(total: total, products: @basket.products) %></li>
    </ul>
  </div>

<% else %>
  <br><h1>Twój koszyk jest pusty!</h1>
<% end %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<table>
    <thead>
      <tr height="25">
        <th></th>
        <th>Nr zamówienia</th>
        <th>Data złożenia zamówienia</th>
        <th>Wartość zamówienia</th>
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <tr height='10'></tr>
      <% @orders.each do |order| %>
        <tr height='30'>
          <td><b><%= order.id %></b></td>
          <td></td>
          <td><b><%= order.created_at.to_date %></b></td>
          <td><b><%= order.total.to_s + '0 zł' %></b></td>
          <td><b><%= order.status.humanize %></b></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/record/index.html.erb
<table class="table table-striped">
  <thead>
    <tr height="25">
      <th></th>
      <th><%= sortable_column "Album", :column => "record_name" %></th>
      <th><%= sortable_column "Artysta", :column => "artist_name"  %></th>
      <th><%= sortable_column "Gatunek", :column => "genre" %></th>
      <th><%= sortable_column "Rok wydania", :column => "release_year" %></th>
      <th><%= sortable_column "Cena", :column => "price" %></th>
      <th></th>
      <th>
        <%= form_tag records_path, :method => 'get' do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Szukaj", :name => nil %>
          </p>
        <% end %>
      </th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr height='20'></tr>
    <% @records.each do |record| %>
      <tr height="60">
        <% album_cover_path = 'album covers/' + record.name.downcase.gsub(/\s/,'_') + '.jpg' %>
          <% album_cover_path = 'question_mark.png' if !File.exist?("#{Rails.root}/app/assets/images/" + album_cover_path) %>
        <td><%=image_tag(album_cover_path, height: '45', width: '45')%></td>
        <td><%= record.name %></td>
        <td><%= record.artist.name %></td>
        <td><%= record.genre.name %></td>
        <td><%= record.release_year %></td>
        <td><%= record.price.to_s + '0 zł' %></td>
        <td><%= button_to 'Więcej', record %></td>
        <td><%= button_to 'Dodaj do koszyka', add_record_path(record) %></td>
      </tr>
      <tr height="5"></tr>
      <tr height="5"></tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @records %>

<br>

app/views/record/show.html.erb
<% album_cover_path = 'album covers/' + @record.name.downcase.gsub(/\s/,'_') + '.jpg' %>
<% album_cover_path = 'question_mark.png' if !File.exist?("#{Rails.root}/app/assets/images/" + album_cover_path) %>
<h1><%=image_tag(album_cover_path, height: '200', width: '200')%></h1><br>

<p align='left'>Informacje o płycie</p><br>

<div class="action_buttons_header" style="text-align: right;">
  <ul style="list-style: none">
    <li>Cena: <%= @record.price.to_s + '0 zł' %></li>
    <li>Dostępna ilość: <%= 50 %></li><br>
    <li><%= button_to 'Dodaj do koszyka', add_record_path(@record) %></li>
  </ul>
</div>

app/views/users/edit.html.erb
<h1>Edytuj konto</h1><br>

<center>
  <%= form_for @user do |f| %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p><br>
    <p>
      <%= f.label :firstname, "Imię" %><br />
      <%= f.text_field :firstname %>
    </p><br>
    <p>
      <%= f.label :lastname, "Nazwisko" %><br />
      <%= f.text_field :lastname%>
    </p><br>
    <p>
      <%= f.label :password, "Hasło" %><br />
      <%= f.password_field :password %>
    </p><br>
    <p>
      <%= f.label :password_confirmation, "Potwierdź hasło" %><br />
      <%= f.password_field :password_confirmation %>
    </p><br>
    <p class="button"><%= f.submit "Zatwierdź"%></p><br>
  <% end %>
</center>

app/views/users/new.html.erb
<h1>Zarejestruj się</h1><br>

<center>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <ul>
          <% @user.errors.values.each do |messages| %>
            <% messages.each do |message| %>
              <li><%= message %><br></li>
            <% end %>
          <% end %><br>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email, :size => '50' %>
    </p><br>
    <p>
      <%= f.label :password, "Hasło" %><br />
      <%= f.password_field :password %>
    </p><br>
    <p>
      <%= f.label :password_confirmation, "Potwierdź hasło" %><br />
      <%= f.password_field :password_confirmation %>
    </p><br>
    <p class="button"><%= f.submit "Rejestracja"%></p><br>
  <% end %>
</center>

app/views/users/show.html.erb
<h1>Twoje dane</h1><br>

<center>
  <table>
    <tr height="25">
      <td><b>Email: </b></td>
      <td><%= @user.email %></td>
    </tr>
    <tr height="25">
      <td><b>Imię:</b></td>
      <td><%= @user.firstname %></td>
    </tr>
    <tr height="25">
      <td><b>Nazwisko:</b></td>
      <td><%= @user.lastname %></td>
    </tr>
    <tr></tr>
    <tr></tr>
    <tr height="40">
      <td> </td>
      <td><%= button_to 'Zmień dane', edit_user_path(@user.id) %></td>
      <td><%= button_to 'Usuń konto', user_path(@user.id), :method => :delete, data: {:confirm => 'Jesteś pewien?'} %></td>
    </tr>
  </table>
</center>