config/routes.rb
Rails.application.routes.draw do
 
  get 'orders/new'

  get 'orders/create'

  get 'sessions/new'

  get 'users/new'

  get 'record/index'

  get 'record/show'

  get 'genre/index'

  get 'genre/show'

  get 'admin', to: 'admin/admin_users#index'

  get '/index', to: 'welcome#index', as: 'welcome'

  get 'record/index', to: 'record#index', as: 'records'

  post 'record/index'
  post 'record/:id', to: 'record#show'
  post 'record/:id/add', to: 'record#add', as: 'add_record'

  post '/index', to: 'welcome#index'

  get "/log_in", to: "sessions#new", as: "log_in"
  post "/log_in", to: "sessions#create"

  get "/log_out", to: "sessions#destroy", as: "log_out"

  get "/sign_up", to: "users#new", as: "sign_up"

  post '/users', to: 'users#create'
  post 'users/:id', to: 'users#show'
  post 'users/:id/edit', to: 'users#edit', as: 'edit_user'
  delete '/users/:id', to: "users#destroy", as: 'destroy_user'

  post '/baskets/:id', to: 'baskets#show', as: 'show_basket'
  post '/baskets/:id/remove_product(:record_id)', to: 'baskets#remove_product', as: 'remove_product'

  post 'orders/create', to: 'orders#create', as: 'create_order'
  post 'orders/index', to: 'orders#index', as: 'orders_index'

  resources :artist, :genre, :record, :sessions, :users, :baskets, :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :records
  validates :name, presence: true, uniqueness: true
end

app/models/basket.rb
class Basket < ActiveRecord::Base
  serialize :products, Hash

  def add(record)
    unless products[record]
      products[record] = 1
    else
      products[record] += 1
    end
    products
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :records
  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  serialize :products, Hash

  validates :total, presence: true

  enum status: [ :anulowane, :przyjęte_do_realizacji, :w_trakcie_realizacji, :wysłane ]
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :artist
  belongs_to :genre

  validates_presence_of :artist , :genre, :name
  validates_associated :artist , :genre
  validates :price, 
    :numericality => {:greater_than_or_equal_to => 0},
    presence: true
  validates :release_year, 
    :numericality => {:greater_than => 1500, :less_than_or_equal_to => Time.now.year},
    presence: true

  def self.search_(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders

  has_secure_password
  
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_confirmation_of :password, :message => 'Hasła do siebie nie pasują', :allow_blank => true
  validates :password,:presence => {:message => 'Hasło jest wymagane!'}
  validates :password_confirmation,:presence => {:message => 'Potwierdzenie hasła jest wymagane!'}
  validates_length_of :password, :minimum => 5, :message => 'Za krótkie hasło (co najmniej 5 znaków)', :allow_blank => true
  validates_presence_of :email, :message => 'Adres email jest wymagany!'
  validates_uniqueness_of :email, :message => 'Użytkownik o podanym adresie już istnieje!'
  validates :email, :format => EMAIL_REGEX, :allow_blank => true

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  helper_method :remove_product

  def new
    @basket = Basket.new(params[:id])
  end

  def create
    @basket = Basket.new(params[:id])
    @basket.save!
  end

  def show
    @basket = Basket.find(session[:basket_id])
  end

  def remove_product
    basket = Basket.find(session[:basket_id])
    record = Record.find(params[:record_id])
    basket.update(products: basket.products.except(record))
    redirect_to show_basket_path(basket)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authorize

  def index
    @orders = Order.where(user_id: current_user)
  end

  def create
    @order =  Order.new(user: current_user, total: params[:total], products: params[:products])
    session[:basket_id] = nil
    if @order.save!
      redirect_to root_path, notice: "Przyjęto zamówienie nr #{@order.id}"
    else 
      redirect_to root_path, notice: 'Nie udało się'
    end
  end

  def show
  end

end

app/controllers/record_controller.rb
class RecordController < ApplicationController
  handles_sortable_columns

  def index
    @records = Record.all

    order = sortable_column_order do |column, direction|
      case column
        when "record_name" 
          "name #{direction}"
        when "artist_name"
          #@records = @records.includes(:artist)
          #{}"artist.name #{direction}"
        when "genre"
          #@records = @records.includes(:genre)
          #{}"genre.name #{direction}"
        when "release_year"
          "release_year #{direction}"
        when "price"
          "price #{direction}"
      end
    end

    @records = @records.search_(params[:search]).order(order).paginate(per_page: 10, page: params[:page])
  end

  def show
    @record = Record.find(params[:id])
  end

  def add
    session[:basket_id] ||= Basket.create.id
    record = Record.find(params[:id])
    Basket.find(session[:basket_id]).update(products: Basket.find(session[:basket_id]).add(record))
    redirect_to records_path, notice: 'Dodano do koszyka'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Zarejestrowano!"
    else
      flash[:alert] = []
      @user.errors.values.flatten.each do |message|
        flash[:alert] << message    
      end
      redirect_to sign_up_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    session[:user_id] = nil
    user.destroy
    redirect_to root_path
  end

  def update
    user = User.find(params[:id])
    if user.update_attributes(user_params)
      redirect_to user_path(user[:id]), notice: "Zaktualizowano dane"
    else
      redirect_to edit_user_path(user[:id]), notice: "Edycja nie powiodła się"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def initialize_basket
    basket = Basket.create
    session[:basket_id] = basket.id
  end
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Record Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
</head>
<body style="background-color: #ffe1cf;">

  <h1 style="font-family : Courier; color: white; background-color: black; font-size: 400%;", align="center"><b>Record Store</b></h1>

  <div class="element1" display="inline-block" id="element1">
    <nav class="navbar navbar-default" role="navigation">

      <ul class="nav navmenu-nav">
        <li><%= link_to "Strona główna" , welcome_path %></li><br>
        <li><%= link_to "Płyty" , records_path%></li><br>
        <% if session[:basket_id].nil? %>
          <% initialize_basket %>
        <% end %>
        <li><%= link_to "Mój koszyk" , show_basket_path(Basket.find(session[:basket_id])), class: "active"%></li><br>
        <% if current_user %>
          <li><%= link_to "Moje zamówienia", orders_index_path, :method => :post, class: "active"%></li><br>
          <li><%= link_to "Moje konto", current_user, class: "active"%></li><br>
        <% end %>
      </ul>
    </nav>
  </div>

  <div id="element3">
    <div id="user_nav">
      <% if current_user %>
        Zalogowany jako: <br>
        <b><%= current_user.email %></b><br><br>
        <%= link_to "Wyloguj", log_out_path %>
      <% else %>
        <%= link_to "Zarejestruj się", sign_up_path %> lub
        <%= link_to "Zaloguj", log_in_path %>
      <% end %>
    </div><br>

    <% flash.each do |name, message| %>
    <% if message.kind_of?(Array) %>
      <b>Podano nieprawidłowe dane:</b><br><br>
      <% message.each do |msg| %>
        <b style="color:#990000"><%= content_tag :div, msg, :id => "flash_#{name}" %></b><br>
      <% end %>
    <% else %>
      <b><%= content_tag :div, message, :id => "flash_#{name}" %></b>
    <% end %>
    <% end %>
  </div>

  <div id="element2">
    <%= yield %>
  </div>


</body>
</html>